package com.smart5g

import android.content.Context
import android.content.Intent
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.text.SimpleDateFormat
import java.util.*

data class RoomResult(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val score: Int?,
    val grade: String? = null,
    val confidence: String? = null,
    val fingerprint: String? = null,
    val rsrp: Int?,
    val spread: Int?,
    val perf: Perf,
    val networkType: String? = null,
    val operator: String? = null,
    val timestamp: Long = System.currentTimeMillis()
) {
    val formattedDate: String
        get() = SimpleDateFormat("MMM d, h:mm a", Locale.getDefault()).format(Date(timestamp))
}

class RoomRepository(context: Context) {
    private val prefs = context.getSharedPreferences("smart5g_rooms_data", Context.MODE_PRIVATE)
    private val gson = Gson()
    private val key = "saved_room_tests"

    fun loadRooms(): List<RoomResult> {
        val json = prefs.getString(key, null) ?: return emptyList()
        return runCatching {
            val type = object : TypeToken<List<RoomResult>>() {}.type
            gson.fromJson<List<RoomResult>>(json, type) ?: emptyList()
        }.getOrDefault(emptyList())
    }

    fun saveRoom(room: RoomResult): List<RoomResult> {
        val current = loadRooms().toMutableList()
        val index = current.indexOfFirst { it.name.equals(room.name, ignoreCase = true) }
        if (index != -1) {
            current[index] = room
        } else {
            current.add(0, room)
        }
        prefs.edit().putString(key, gson.toJson(current)).apply()
        return current
    }

    fun deleteRoom(id: String): List<RoomResult> {
        val updated = loadRooms().filterNot { it.id == id }
        prefs.edit().putString(key, gson.toJson(updated)).apply()
        return updated
    }

    fun clearAll(): List<RoomResult> {
        prefs.edit().remove(key).apply()
        return emptyList()
    }

    fun createShareIntent(rooms: List<RoomResult>): Intent {
        val best = rooms.maxByOrNull { it.score ?: -1 }
        val sb = StringBuilder()
        sb.appendLine("📶 Smart5G Home & Office Coverage Survey")
        sb.appendLine("Total Rooms Surveyed: ${rooms.size}")
        if (best != null) {
            sb.appendLine("⭐ Recommended Spot for 5G Gateway / Router: ${best.name} (${best.score ?: 0}/100)")
            best.fingerprint?.let { sb.appendLine("   Classification: $it (${best.confidence ?: "CONFIRMED"} Confidence)") }
        }
        sb.appendLine("----------------------------------------")
        rooms.sortedByDescending { it.score ?: -1 }.forEachIndexed { idx, r ->
            val star = if (r.id == best?.id && rooms.size > 1) " ⭐ BEST" else ""
            sb.appendLine("${idx + 1}. ${r.name}$star")
            sb.appendLine("   Score: ${r.score ?: 0}/100 | ${r.grade ?: "N/A"}${r.fingerprint?.let { " • $it" } ?: ""}")
            r.confidence?.let { sb.appendLine("   Confidence: $it") }
            sb.appendLine("   Network: ${r.networkType ?: "Cellular"} (${r.operator ?: "Unknown"})")
            sb.appendLine("   Signal (RSRP): ${r.rsrp?.let { "$it dBm" } ?: "N/A"} (Spread: ${r.spread?.let { "$it dB" } ?: "N/A"})")
            sb.appendLine("   Download: ${r.perf.down?.let { "%.1f Mbps".format(it) } ?: "N/A"} | Upload: ${r.perf.up?.let { "%.1f Mbps".format(it) } ?: "N/A"}")
            sb.appendLine("   Ping: ${r.perf.latMs?.let { "%.0f ms".format(it) } ?: "N/A"} | Jitter: ${r.perf.jitterMs?.let { "%.1f ms".format(it) } ?: "N/A"}")
            sb.appendLine("   Date: ${r.formattedDate}")
            sb.appendLine()
        }
        sb.appendLine("Generated by Smart5G App")

        return Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Smart5G Coverage Survey Report")
            putExtra(Intent.EXTRA_TEXT, sb.toString())
        }
    }

    fun loadSpeedConfig(): SpeedTestConfig {
        val json = prefs.getString("speed_test_config", null) ?: return SpeedTestConfig()
        return runCatching {
            gson.fromJson(json, SpeedTestConfig::class.java) ?: SpeedTestConfig()
        }.getOrDefault(SpeedTestConfig())
    }

    fun saveSpeedConfig(config: SpeedTestConfig) {
        prefs.edit().putString("speed_test_config", gson.toJson(config)).apply()
    }
}

data class SpeedTestConfig(
    val serverName: String = "Cloudflare Global Anycast",
    val baseUrl: String = "https://speed.cloudflare.com",
    val durationSeconds: Int = 5,
    val streams: Int = 4,
    val uploadEnabled: Boolean = true
)
